name: Deploy Docker image to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .                 # Explicit build context (root directory)
          file: ./Dockerfile         # Explicit Dockerfile path
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tmdb-addon-redis:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/tmdb-addon-redis:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tmdb-addon-redis:${{ env.TAG }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/tmdb-addon-redis:latest
